services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=dev1
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
